server:
  port: 9527
## id:路由的id，获取方法
## uri提供路由服务的地址
## predicate 断言路径相匹配 进行路由
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
      routes:
        - id: payment_Get
#          uri: http://localhost:8002
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/getPaymentById/**
        - id: payment_port
#          uri: http://localhost:8002
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/port
#            - Host=**.lijuny.com
#            - Cookie=username,lijuny
#            - Header=X-Request-Id,\d+
eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
      register-with-eureka: true
      fetch-registry: true