server:
  port: 80

spring:
  application:
    name: nacos-mine-consumera
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
